name: Deploy 

on: 
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Docker Compose Build
          run: sudo docker-compose -f docker-compose.yml --build -d